/*
 * Standard types definitions 
 */

#ifndef STD_TYPES_H
#define STD_TYPES_H

/* These hash values have been generated by the compiler and then pasted in */
#define STD_DATE "u'#date#2087874221213244225'"
#define MSG_ATTR_TYPE "#msgAttr#3816628149631153685"
#define MONITOR_TYPE "#_monitor_protocol#11286750358879"
#define FIL_MODE "u'#_file_permission#7707581460850275476'"
#define PRC_STATE "u'#_process_state#1582288624734862776'"
#define OPEN_MODE "u'#_file_open_mode#79783829933682672'"
#define DEBUG_TYPE "#debugMsgType#6155703034433634929"

#define FILE_STAT "u'#_file_status#3771354758848855244'"
#define FILE_TYPE "u'#_file_type#6442707525338592816'"

#define SYS_ERROR "u'#error#8358562035060134174'"

#endif
