\input psfig.tex
\input texinfo
@c %**start of header
@setfilename alex.info
@settitle Alex Reference Manual
@c %**end of header
@smallbook
@setchapternewpage odd
@include version.texi

@dircategory Programming
@direntry
* alex: (alex).		April LEXical parser generator
@end direntry

@titlepage
@title April LEXical parser generator
@subtitle Version 0.0, last updated @value{UPDATED}
@author F.G. McCabe @email{fgm@@fla.fujitsu.com}

@c  The following two commands
@c  start the copyright page.
@page
@vfill
@copyright{} 1994-1999 Fujitsu Labs of America Inc. and F.G. McCabe

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by Fujitsu Labs of America.
@end titlepage
     
@node Top
@top April LEXical parser generator

@noindent
This is the 
@ifinfo
on-line
@end ifinfo 
Reference Manual for the April LEXical parser generator -- known as
@code{Alex}, version 0.0, last updated on @value{UPDATED}.
@refill

This manual offers an in-depth and complete description of the
April LEXical parser generator, how it can be used to generate a
tokeniser for @code{April} and a little of the theory behind it.


@ifinfo
@copyright{} 1999 Fujitsu Labs of America inc. and F.G. McCabe

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by Fujitsu Labs of America.
@end ifinfo


@menu
* Copying::                     Your rights and freedoms
* Introduction::                Summary of the basic concepts
* Using Alex::                  Writing a rule file
* Background theory::           How it works
* Listing of token::            Sample @code{Alex} program
* Alex rule grammar::           Formal definition of @code{Alex} programs
* Concept index::
@end menu

@include gpl.texi
@include intro.texi
@include using.texi
@include theory.texi
@include token.texi
@include grammar.texi

@node Concept index
@unnumbered Concept index
@printindex cp

@c @node Function index
@c @unnumbered Standard function index
@c @printindex fn

@summarycontents
@contents
@bye

